name: Katherine Yang
description: Personal website and portfolio of Katherine Yang, creative technologist.
author: Katherine Yang
author_email: whykatherine@gmail.com
github_username: whykatherine
url: https://whykatherine.github.io
logo: /assets/img/monogram.svg
links:
  - https://github.com/whykatherine
  - https://www.instagram.com/kayserifserif
  - https://www.linkedin.com/in/whykatherine
  - https://www.twitter.com/bookwormgirl910
lang: en_GB
plugins:
  - jekyll-seo-tag
# google_analytics: UA-109421117-1