name: Katherine Yang
description: Katherine Yang is making things in the pursuit of poetic tech.
author: Katherine Yang
author_email: whykatherine@gmail.com
github_username: whykatherine
url: https://whykatherine.github.io
logo: /assets/img/monogram.svg
links:
  - https://github.com/whykatherine
  - https://www.instagram.com/kayserifserif
  - https://www.twitter.com/bookwormgirl910
lang: en_GB
plugins:
  - jekyll-seo-tag